Fix/dash eslin commit check (#518)
* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* testing hook

* pre commit hooks

* pre commit updated

* pre commit updated

* pre commit updated

* fix: eslintrc react fix

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing commit

* testing lint

* testing lint -- 2

* testing lint -- 3

* added linting

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
+
+if [ ! -x "$ESLINT" ]; then
+  echo "\t\033[41mPlease install ESlint\033[0m (npm i --save --save-exact --dev eslint)"
+  exit 1
+fi
+
 exec 1>&2
 git diff --cached --name-status | while read st file; do
     # skip deleted files
@@ -8,6 +15,13 @@ git diff --cached --name-status | while read st file; do
         git reset
         git checkout -- Parse-Dashboard/parse-dashboard-config.json
         echo "[Error] Can not commit parse dashboard config file: $file"
+        exit 1
+    fi
+    "$ESLINT" "$file"
+    if [ "$?" = 1 ]; then
+        git reset
+        git checkout -- $file
+        echo "[Error] eslint failed for file: $file"
         exit 1
     fi
 done
